
    
server:  port: 2525  

management:  endpoints:    web:      exposure:        include:        - "*"
# ---

#spring:#  h2:#    console:#      enabled: true
#      path: /h2
#  datasource:#    url: jdbc:h2:file:C:/h2data/sample 
#    username: sa
#    password: 
#    driver-class-name:org.h2.Driver 
    