spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
        datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan  boot:    admin:      client:        url:        - http://localhost:1010
    
server:  port: 2020  

management:  endpoints:    web:      exposure:        include:        - "*"
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql: trace 

# ---

#spring:#  h2:#    console:#      enabled: true
#      path: /h2
#  datasource:#    url: jdbc:h2:file:C:/h2data/sample 
#    username: sa
#    password: 
#    driver-class-name:org.h2.Driver 
    