 
spring:
  application:
    name: api-gatway
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka      

ribbon:
  eureka:
    enabled: false

zuul:
 routes:
   tax-service:
     path: /tax-service/**
     url: http://localhost:2022/

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"      
        
server:
  port: 6060
  
          