server:
  port: 1010
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vatsank/spring-config-server.git      discovery:        enabled: true
  application:    name: config-server
eureka:  client:    fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: http://localhost:8761/eureka
              
