
  
spring:
  application:
    name: greeting-service
 
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka ,http://eureka-peer2:8771/eureka      

      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"      
        
server:
  port: 4242
  

          