spring:
  profiles:
  - eureka-peer1
  application:
    name: eureka-clustered
eureka:
  instance:
    hostname: eureka-peer1
    appname: eureka-clustered 
  client:
    service-url:
      defaultZone: http://localhost:8771/eureka
    register-with-eureka: true 
    fetch-registry: true
server:
  port: 8761          

---

spring:
  profiles:
  - eureka-peer2
  application:
    name: eureka-clustered
eureka:
  instance:
    hostname: eureka-peer2
    appname: eureka-clustered 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true 
    fetch-registry: true
server:
  port: 8771          

  